5 acceptance testing
Halvanhelv/QnA pull request #4
Opened 2020-06-29 17:04 UTC by SynthesisOne

1. Реализовать следующие истории, начиная с acceptance-тестов (если они уже реализованы, покрыть acceptance-тестами):
  - Пользователь может создавать вопрос
  - Пользователь может просматривать список вопросов
  - Пользователь, находясь на странице вопроса, может написать ответ на вопрос (т.е. форма нового ответа должна быть прямо на странице вопроса, без перехода на другую страницу)
  - Пользователь может просматривать вопрос и ответы к нему.

 2. Добавить аутентификацию к проекту, покрыть acceptance-тестами следующие сценарии:
  - Пользователь может войти в систему
  - Пользователь может выйти из системы
  - Пользователь может зарегистрироваться в системе

 3. Реализовать следующие истоиии:
  - Только аутентифицированный пользователь может создавать вопросы и ответы
  - Автор может удалить свой вопрос или ответ, но не может удалить чужой вопрос/ответ
 

Примечание: 

- Во всех формах ставьте опцию local: true, чтобы избежать возможных проблем с отображением ошибок при реальной работе в браузере. Подробнее об этом будет рассказано в следующем уроке.

Рекомендации:

 - Можно записать основные сценарии, без реализации, а затем писать их один за другим. Для этого просто напишите  
scenario "some description"
 такие сценарии будут отображаться как pending, то есть ждущие реализации. Это для того, чтобы вы не забыли их реализовать.
 - Написали сценарий, перешли на уровень unit-тестов. Здесь двигаемся мелкими шагами "тест-код-рефакторинг, тест-код-рефакторинг". Некоторые вещи можно будет описать сразу, например, валидации и ассоциации, а какие-то будут сложнее, здесь лучше двигаться постепенно.
 - Далее описыавем следующий сценарий и опять на уровень unit-тестов и так далее, пока не реализуем все сценарии
 - После того, как все сценарии проходят, подумайте, может быть есть еще какие-то сценарии, которые вы не описали. Если так, то добавьте их.
 - Для аутнетификации лучше всего использовать Devise, т.к. впоследствии он нам еще пригодится

2020-06-30 09:25 UTC, vkurennov requested changes

2020-06-30 09:25 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user == answer.user
1. Такая проверка понадобится не раз и не только в контроллерах, поэтому лучше ее вынести в метод `User#author_of?` (не забудь тесты написать на этот метод)
2. Не очень оптимальная конструкция. тут ты загружаешь ассоциацию user у ответа, т.е. делаешь запрос в базу и занимешь память этим объектом, но сам объект при этом не используется. А ведь у ответа уже есть загруженный атрибут user_id и достаточно сравнить по нему. Общее правило: сравнивать по id, присваивать по объектам.

2020-06-30 09:25 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user == question.user
замени на вызов `User#author_of?`

2020-06-30 09:25 UTC, vkurennov commented on app/views/answers/_form.slim
> +=form_with url: question_answers_path(question),local: true do |f|
тут перед формой стоит добавить вывод ошибок валидации.

2020-06-30 09:25 UTC, vkurennov commented on app/views/answers/_form.slim
> +=form_with url: question_answers_path(question),local: true do |f|
и надо сделать нормальную форму через with: model, а не через url. так сразу у объекта поля будут связываться с нужными полями модели, а при редактировании или ошибках валидации, туда будут подставляться значения из полей модели

2020-06-30 09:25 UTC, vkurennov commented on app/views/answers/_form.slim
> +  = f.text_field 'answer[body]', id: :body
почему text_field? ответ же может быть многострочным, тут text_area нужна

2020-06-30 09:25 UTC, vkurennov commented on app/views/layouts/application.html.erb
>    <body>
лейаут стоит перевести на slim

2020-06-30 09:25 UTC, vkurennov commented on app/views/layouts/application.html.erb
> +  <%=render 'shared/flash' %>>
после  erb-скобок (<%  и <%= ) и перед закрывающими принято ставить пробел - это облегчает чтение. посмотри, как в строках где выводятся алерты

2020-06-30 09:25 UTC, vkurennov commented on app/views/layouts/application.html.erb
> +  <%if current_user %>
а если не залогинен? стоит, наверное, ссылку на вход показать

2020-06-30 09:25 UTC, vkurennov commented on app/views/questions/show.html.slim
> +-if @answer
зачем повторение условия, оно же точно такое же как в первой строке

2020-06-30 09:25 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = render 'shared/errors',resource: @answer
это надо в паршл формы переместить

2020-06-30 09:25 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  -question = @answer.question
вот это вообще всего не должно быть в виде, если нужно подготовить данные для вида - сделай это в контроллере

2020-06-30 09:25 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  -question = self.question #Если не писать else блок то question почему то всегда nil
ну так ты переопределяешь же здесь идентификатор 'question', по идее это метод в котнроллере, но ты здесь используешь его как переменную, соответсвенн, интерпретатор понимает, что это переменная, значения в ней нет, вот и возвращает nil.

надо просто избавиться от этого if вообще и готовить данные в контроллере. подсказка: чтобы метод question вовзращал то, что нужно, нельзя написать `question =`, потому что это метод, а не переменная, и метода-сеттера не определено. Вместо этого нужно присваивать значение инстанс-переменной, в которой хранится объект, тогда метод будет возвращать нужное значение. Посмотри внимательно на реализацию метод question в контроллере, надеюсь, станет ясно.

2020-06-30 09:25 UTC, vkurennov commented on app/views/questions/show.html.slim
> +=button_to 'Delete',question_path(question),method: :delete
зачем показывать кнопку на удаление всем подряд? пусть только автор ее видит

2020-06-30 09:25 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  =button_to 'Delete Answer',answer_path(f),method: :delete
то же самое: пусть только автор видит кнопку на удаление. и после запятых и равно и других знаков препинания ставятся проблеы (причем не только в коде, но и в обычном тексте). Аккуратный и стильный код  - признак профессионализма, у тебя пока наоборот - выдает новичка. Не надо так делать, ты же этот код потом работодателю будешь показывать и это точно сыграет в жирный минус

2020-06-30 09:25 UTC, vkurennov commented on db/migrate/20200629133637_create_question_user_reference.rb
> +    add_reference(:questions,:user,foreign_key:true,on_delete: :cascade)
пробелы!!!!

2020-06-30 09:25 UTC, vkurennov commented on db/migrate/20200629160917_create_answer_user_reference.rb
> +    add_reference(:answers, :user, foreign_key: true)
вот здесь же есть пробелы и сразу все читается легче

2020-06-30 09:25 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
тут нужен тест на связь с залогиненным юзером

2020-06-30 09:25 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { answer: attributes_for(:answer), question_id: question, user: user } }.to change(question.answers, :count).by(1)
нет, user не передается в параметрах, мы его получаем в контроллере через current_user, здесь его передавать не нужно, в отличие от вопроса, id которого в самом url присутсвует, т.к. у нас вложенные ресурсы

2020-06-30 09:25 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>        it 'assigns the requested answer to @answer' do
это лишний тест потому что ты уже проверил ассоциацию вопроса и ответа в предыдущем (обрати внимание, что ты в change проверяешь)

2020-06-30 09:25 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
блоки describe, context, it отделяются друг от друга пустыми строками. это то же самое, что с пробелами - облегчает чтение. как абзацы в тексте - отделяют логические части друг от друга

2020-06-30 09:25 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'DELETE #destroy' do
тут лучше разделить на 2 контекста тесты: для автора и для не-автора, чтобы логически разбить их

2020-06-30 09:25 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      it 'deletes the answer' do
отделяй пустыми строками блока кода, такие как it, describe, context. и не только здесь, а **во всех тестах**

2020-06-30 09:25 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
тут нужен тест на связь с залогиненным юзером

2020-06-30 09:25 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
разделяй блоки пустыми строками!!!

2020-06-30 09:25 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    context 'delete user created question' do
давай более внятные имена, например, "author of question"

2020-06-30 09:25 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { delete :destroy, params: { id: question } }.to change(Question, :count).by(-Question.count) # не знал какую функцию использовать для определения того что все ответы у вопроса были уд
это вообще какая-то ерунда. то есть, если в системе 25 вопросов, то удалив один, удаляются все? зачем?
если же ты хотел проверить каскадное удаление **ответов**, то этого вообще не нужно делать в тестах контроллера, это на уровне модели тестируется через опции ассоциации.

2020-06-30 09:25 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    it 'Attempting to delete a question from a non-current user' do
а вот этот тест тогда стоит убрать в контекст "не-автор"

2020-06-30 09:25 UTC, vkurennov commented on spec/factories/answers.rb
> +    question_id { nil }
зачем создавать заведомо невалидный объект через фабрики? они умеют работать с ассоциациям, причем довольно прозрачно. если имя ассоциации и фабрики совпадает, то достаточно указать лишь название ассоциации, например:


```
  factory :answer do
    body { 'MyAnswer' }
    question
    user
  end
```

а при использвании  в  тестах всегда можно заменить ассоциации:

```
let(:question) { create(:question) }
let(:answer) { create(:answer, question: question) }
```

2020-06-30 09:25 UTC, vkurennov commented on spec/factories/questions.rb
>  FactoryBot.define do
см. замечания к фабрике ответов

2020-06-30 09:25 UTC, vkurennov commented on spec/factories/users.rb
> +  end
отделяй пустыми строками методы и блоки кода друг от друга

2020-06-30 09:25 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +require 'rails_helper'
пустые строки между тестами и другими блоками кода

2020-06-30 09:25 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +require 'rails_helper'
пустые строки между тестами и другими блоками кода

2020-06-30 09:25 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +  scenario 'User try delete his answer' do
тут надо проверить, что до удаления текст ответа есть на странице, а после  - то, что его нет

2020-06-30 09:25 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +  scenario 'User try delete not your question' do
нужен такой же тест для незалогиненного юзера

2020-06-30 09:25 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    click_on 'Delete Answer'
лучше просто не показыввать ссылку и это и проверить

2020-06-30 09:25 UTC, vkurennov commented on spec/features/question/create_spec.rb
> +require 'rails_helper'
пустые строки между тестами и другими блоками кода

2020-06-30 09:25 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +require 'rails_helper'
пустые строки между тестами и другими блоками кода

2020-06-30 09:25 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +  scenario 'User try delete not your question' do
те же замечания, что и для аналогичного теста для ответов

2020-06-30 09:25 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +require 'rails_helper'
пустые строки между тестами и другими блоками кода

2020-06-30 09:25 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +    expect(page).to have_content 'MyString'
нужно проверить **список** ответов, т.е. несколько. причем, они должны быть разными (используй sequence в фабриках для этого)

2020-06-30 09:25 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +    expect(page).to have_content 'MyString'
ответы также нужно проверить списком и они должны быть разными.

2020-06-30 09:25 UTC, vkurennov commented on spec/features/user/sign_in_spec.rb
> +feature 'User can sign in', " аналог discribe
пустые строки между тестами и другими блоками кода

2020-06-30 09:25 UTC, vkurennov commented on spec/features/user/sign_out_spec.rb
> +require 'rails_helper'
пустые строки между тестами и другими блоками кода

2020-06-30 09:25 UTC, vkurennov commented on spec/features/user/sign_up_spec.rb
> +require 'rails_helper'
пустые строки между тестами и другими блоками кода

2020-06-30 09:25 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
в моделях мы обычно пишем сначала ассоциации, потом валидации, в тестах тот же порядок

2020-07-01 11:59 UTC, SynthesisOne commented on spec/controllers/answers_controller_spec.rb
> +      before { patch :update, params: { id: answer_static, answer: attributes_for(:answer, :invalid) } }
Можно ли тут как то передать свои поля в фабрику при вызове фабрики, что бы я точно знал какие у меня поля в фабрике а иначе sequence создает динамические данные и они зависят от того в каком порядке вызывается тест, временным решением стало создать ``` let(:answer_static) { create(:answer, :static, user: user, question: question) }``` где в trait уже есть статические данные, есть ли возможность игнорировать sequence в некоторых тестах?

2020-07-01 14:29 UTC, vkurennov requested changes

2020-07-01 14:29 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, except: %i[index show] # except за исключением
пустая строка после before_action и перед create

2020-07-01 14:29 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      # redirect_to @answer.question
а вот здесь после else и перед end пустые строки как раз лишние

2020-07-01 14:29 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  before_action :authenticate_user!, except: %i[index show] # except за исключением
пустая строка

2020-07-01 14:29 UTC, vkurennov commented on app/models/question.rb
>    validates :body, :title, presence: true
между блоком ассоциаций и валидаций также ставится пустая строка

2020-07-01 14:29 UTC, vkurennov commented on app/views/answers/_form.slim
> += form_with model: [question,answer],local: true do |f|
пробел после запятой

2020-07-01 14:29 UTC, vkurennov commented on app/views/questions/new.html.slim
> += render 'shared/errors',resource: @question
пробел после запятой

2020-07-01 14:29 UTC, vkurennov commented on app/views/questions/show.html.slim
> +-if current_user && current_user.author_of?(question)
можно избавиться от стсоавного условия, применив [safe navigation operator](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/)

2020-07-01 14:29 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  -if current_user &&  current_user.author_of?(f)
тут то же самое

2020-07-01 14:29 UTC, vkurennov commented on app/views/questions/show.html.slim
> +-answers.reload.each do |f|
1. делать релоад в видах плохая идея - лишний запрос, соответсвенно дольше формируется ответ пользователю. я так понимаю, что это для того, чтобы исключить невалидный ответ. вместо этого можно в цикле вставить проверку на `persisted?` у ответа, тогда будут выводиться только сохраненные объекты.
2. Что у тебя за название переменной в блоке? Тут нужно давать осмысленные имена, чтобы было понятно, что в переменной содержится. Ты ответы же перебираешь, вот и назови переменную answer, чтобы было понятно, что там ответ. Руби слоботипизированный язык, поэтмоу важно давать правильные имена, чтобы было понятно, что лежит в переменной.

2020-07-01 14:29 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = button_to 'Delete',question_path(question),method: :delete
пробелы после запятых

2020-07-01 14:29 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    = button_to 'Delete Answer',answer_path(f),method: :delete
пробелы после запятых

2020-07-01 14:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      before { patch :update, params: { id: answer_static, answer: attributes_for(:answer, :invalid) } }
Да, любые атрибуты и ассоциации можно переопределить. Просто пишешь `create(:answer, body: '123', user: some_user)`. Т.е. в фабрике прописываются значения по-умолчанию, но при ее вызове, можно передать свои значения, в том числе создаваемые при помощи sequence

2020-07-01 14:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      before { patch :update, params: { id: answer_static, answer: attributes_for(:answer, :invalid) } }
либо можно не переопределять параметры в этом тесте, а написать его через  `to_not change(answer, :body)`

2020-07-01 14:29 UTC, vkurennov commented on spec/factories/answers.rb
>    factory :answer do
а почему ты совсем убрал ассоциации? удобно же, когда нужен просто ответ и не важно с каким юзером он и вопросом связан, просто создать его через `create(:answer)`. а сейчас тебе придется каждый раз их задавать вручную. Ну и без ассоциаций объект невалидный, а фбрика должна создавать валидные объекты по-умолчанию

2020-07-01 14:29 UTC, vkurennov commented on spec/factories/questions.rb
>    factory :question do
нужно добавить ассоциацию с юзером

2020-07-01 14:29 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    expect(page).to have_content 'Answer successfully deleted.'
нужно проверить, что на странице нет текст ответа. у тебя по-прежнему нет этой проверки

2020-07-01 14:29 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +feature 'User can delete his question', "
что-то тут маловато сценариев. их как минимум 3: автор, не автор и незалогиненныю юзер

2020-07-01 14:29 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +    expect(page).to have_content questions.first.title
можно в цикле было проверить

2020-07-01 14:29 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +    expect(page).to have_content answer.body
отступы в блоках. редакторы по идее их сами расставляют

2020-07-01 15:39 UTC, SynthesisOne commented on spec/controllers/answers_controller_spec.rb
> +      before { patch :update, params: { id: answer_static, answer: attributes_for(:answer, :invalid) } }
```      before { patch :update, params: { id: create(:answer, body: '123', user: some_user), answer: attributes_for(:answer, :invalid) } }
``` как то так или вы про ```  это? let(:question)      { create(answer, body: '123', user: some_user) }```

2020-07-01 16:38 UTC, SynthesisOne commented on spec/features/question/delete_spec.rb
> +feature 'User can delete his question', "
> что-то тут маловато сценариев. их как минимум 3: автор, не автор и незалогиненныю юзер

я скрыл все кнопки для удаления и они доступны только тем кто является автором

2020-07-01 16:52 UTC, SynthesisOne commented on app/views/questions/show.html.slim
> +- answers.select(&:persisted?).each do |answer|
в следующем коммите поменял на ```- answers.each do |answer|
  -if answer.persisted?```

2020-07-02 08:44 UTC, vkurennov requested changes

2020-07-02 08:44 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      before { patch :update, params: { id: answer_static, answer: attributes_for(:answer, :invalid) } }
и так и так будет работать,  как видишь, я пример приводил на методе create, а уж где ты его вызывать будешь - значения не имеет, ведь работа метода не зависит от того, где он вызывается. но лучше, конечно, в let выносить.

2020-07-02 08:44 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      before { patch :update, params: { id: answer_static, answer: attributes_for(:answer, :invalid) } }
кстати, не нужно все let  выносить в начало спеки, перед тестами, там должны быть только данные, которые используются во всех или в большинстве тестов, т.е. глобальные. если нужны какие-то данные для конкретного метода, то лучше их помещать в соответсвующем describe или даже context, т.е. ближе к тому, где они нужны. это касается твоего answer_static

2020-07-02 08:44 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    before { login(user) }
нужна пустая строка

2020-07-02 08:44 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +          post :create, params: { question: attributes_for(:question), user: user }
user не передается в параметрах, мы его в контроллере поулчаем, так что убери здесь и везде, где ты его в запросе передаешь

2020-07-02 08:44 UTC, vkurennov commented on spec/factories/answers.rb
>    factory :answer do
если имя ассоциации и фабрики совпадает, можно писать просто имя соотвествующей фабрики/ассоциации без вызова метода `association`:

```
factory :answer do
  user
  question
  # ... 
end
```

2020-07-02 08:44 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +feature 'User can delete his question', "
ну так это и надо проверять, что не-автор и гость не видят кнопок. это и есть сценарии. по идее, у тебя вообще должны быть сначала сценарии и ты должен подумать "так, а как удаление будет работать для не-автора?" - "ну он не должен видеть ссылку на удаление" - "ок, пишем сценарий, что он не видит ее". Потому что пока ни один тест не заставляет тебя скрывать ссылку. Т.е. правильно, когда есть некий тест, который падает и тем самым заставляет нас менять код.

2020-07-02 08:44 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +feature 'User can delete his question', "
1. описание не соответсвует содержанию, здесь удаление ответов описывается, а не вопросов.
2. нужны сценарии для незалогиненного юзера и не-автора.

2020-07-02 13:13 UTC, vkurennov requested changes

2020-07-02 13:13 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +  background do
опять пустые строки забываешь. сложно что ли enter нажать еще раз?

2020-07-02 13:13 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    create_question(question)
вот это не нужно делать, повяторяя все шагию у тебя же через фабрики создаются нужные данные и здесь этого достаточно.

2020-07-02 13:13 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    create_answer(answer)
ну и тут то же самое

2020-07-02 13:13 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +  background do
пустые строки!

2020-07-02 13:13 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    create_question(question)
вопрос сеоздается в 10й строке

2020-07-02 13:13 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +  given(:question)     { user.questions.create(attributes_for(:question)) }
зачем через attributes_for? почему не написать нормально? `create(:question, user: user)`

2020-07-02 13:15 UTC, vkurennov requested changes

2020-07-02 13:15 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +  given(:question) { user.questions.create(attributes_for(:question)) }
почему ответ ты создаешь по-нормальному, а здесь черти-как?

2020-07-02 13:26 UTC, SynthesisOne commented on spec/features/answer/delete_spec.rb
> +    create_question(question)
Да, успел заметить и удалить в следующем коммите

2020-07-02 13:57 UTC, SynthesisOne commented on spec/features/answer/delete_spec.rb
> +  background do
Исправил, прогнал рубокопом

2020-07-02 14:09 UTC, vkurennov approved these changes

2020-07-02 14:14 UTC, merged